"""
Workflow engine driving the full content publishing chain:
  Topic → Produce → Review → Publish → Report
"""

from src.base_client.client import BaseClient
from src.llm.client import LLMClient
from src.agents.manager import ManagerAgent
from src.agents.editor import EditorAgent
from src.agents.reviewer import ReviewerAgent


class WorkflowEngine:
    """Content publishing workflow engine."""

    def __init__(self, base_client: BaseClient, llm: LLMClient):
        self.api = base_client
        self.llm = llm
        self.manager = ManagerAgent(base_client, llm)
        self.editor = EditorAgent(base_client, llm)
        self.reviewer = ReviewerAgent(base_client, llm)

    def run_full_chain(self, topic_title: str, content_title: str,
                       summary: str, category: str, word_count: int) -> dict:
        """
        Full publishing chain:
          Manager creates topic → Editor generates content → Reviewer reviews
          → Manager approves publish → Report generated
        """
        result = {}

        # 1. Manager: create topic
        print("[Manager] Creating topic...")
        task_id = self.manager.create_topic(topic_title, priority="高")
        result["task_id"] = task_id
        print(f"  [OK] Task ID: {task_id}")

        # 2. Manager: assign to editor
        print("[Manager] Assigning to editor...")
        self.manager.assign_to_editor(task_id)
        print(f"  [OK] Assigned")

        # 3. Editor: generate content via LLM
        print("[Editor] Generating content...")
        content_id = self.editor.produce_content(
            task_id, content_title, summary, category, word_count
        )
        result["content_id"] = content_id
        print(f"  [OK] Content ID: {content_id}")

        # 4. Editor: submit for review
        print("[Editor] Submitting for review...")
        review_id = self.editor.submit_for_review(content_id, task_id)
        result["review_id"] = review_id
        print(f"  [OK] Review ID: {review_id}")

        # 5. Reviewer: review the content we just produced
        print("[Reviewer] Reviewing content...")
        content_record = self.api.get_content(content_id)
        content_fields = content_record.fields or {}
        article = content_fields.get("正文全文") or ""
        print(f"  [Reviewer] Article length: {len(article)} chars")

        decision, opinion = self.reviewer.review(
            review_id, article, content_title
        )
        result["review_result"] = decision
        result["review_opinion"] = opinion
        print(f"  [OK] Review: {decision}")
        print(f"  Opinion: {opinion}")

        # 6. Manager: approve publish
        print("[Manager] Approving publish...")
        self.manager.approve_publish(task_id)
        print(f"  [OK] Published")

        # 7. Manager: archive
        print("[Manager] Archiving task...")
        self.manager.archive_task(task_id)
        print(f"  [OK] Archived")

        # 8. Manager: generate operational report
        print("[Manager] Generating operational report...")
        report = self.manager.generate_report()
        result["report"] = report
        print(f"  [OK] Report generated")

        result["status"] = "完成"
        return result

    def run_until_blocked(self) -> list:
        """
        Polling driver: scan tables and advance pending tasks.
        Returns list of triggered actions.
        """
        triggered = []

        # Editor: claim pending tasks
        task = self.editor.pick_task()
        if task:
            print(f"[Poll] Editor picked task: {task['title']}")
            content_id = self.editor.produce_content(
                task["record_id"],
                title=f"Content - {task['title']}",
                summary="Auto-generated by Editor",
                category="运营",
                word_count=1000,
            )
            self.editor.submit_for_review(content_id, task["record_id"])
            triggered.append(f"task:{task['record_id']}")

        # Reviewer: claim pending reviews
        review = self.reviewer.pick_review_task()
        if review:
            print(f"[Poll] Reviewer picked review: {review['record_id']}")
            self.reviewer.approve(review["record_id"])
            triggered.append(f"review:{review['record_id']}")

        return triggered
